export const empty_lectures = {
    "count": 0,
    "next": null,
    "previous": null,
    "results": [],
};

export const lectures = {
    "properes_lectures": "https://api.fib.upc.edu/v2/lectures/properes/",
    "count": 9447,
    "next": "https://api.fib.upc.edu/v2/lectures/?page=44",
    "previous": "https://api.fib.upc.edu/v2/lectures/?page=42",
    "results": [
        {
            "codi": 150522,
            "titol": "Disseny d'activitats PBL i aprenentatge cooperatiu basades en Arduino, per a l'aprenentatge de matèries TIC i electrònica per estudiants de cicles formatius d'electrònica i informàtica.",
            "inici": "2020-06-17T12:50:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "FRANCESC JOSEP ROBERT SANXIS",
            "codirector": "",
            "ponent": "",
            "estudiant": "CARLOS BARAHONA ESTEVE"
        },
        {
            "codi": 150560,
            "titol": "Docència, de la teoria a l'aplicació pràctica en un centre concertat",
            "inici": "2020-06-17T11:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "JUDITH TELLO ARTIGAS",
            "codirector": "",
            "ponent": "",
            "estudiant": "NÚRIA GONZÀLEZ BOLEA"
        },
        {
            "codi": 150652,
            "titol": "Introducció de la nanotecnologia a l'ensenyament secundari",
            "inici": "2020-06-17T11:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ESTER GUAUS GUERRERO",
            "codirector": "",
            "ponent": "",
            "estudiant": "GERARD MASMITJÀ RUSIÑOL"
        },
        {
            "codi": 140685,
            "titol": "Análisis de las estrategias y mecanismos que el centro de formación profesional aplica en el aprendizaje de competencias o habilidades para satisfacer las necesidades empresariales.",
            "inici": "2020-06-17T16:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ENRIC MAYOL SARROCA",
            "codirector": "",
            "ponent": "",
            "estudiant": "ARNALDO SERRANO OROZCO"
        },
        {
            "codi": 140613,
            "titol": "Ús de metodologies actives per a la creació d'activitats contextualitzades al món laboral i disseny d'una unitat formativa",
            "inici": "2020-06-17T10:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "EVA RODRIGUEZ LUNA",
            "codirector": "",
            "ponent": "",
            "estudiant": "ANDREU IBURO OTERO"
        },
        {
            "codi": 150644,
            "titol": "Formació en dibuix digital i ús d'una talladora làser en l'assignatura de Tecnologia de Secundària",
            "inici": "2020-06-17T16:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MARIA PILAR ALMAJANO PABLOS",
            "codirector": "",
            "ponent": "",
            "estudiant": "REMÍ VILADRICH SANTAEULÀLIA"
        },
        {
            "codi": 150559,
            "titol": "Estratègies de centre per fomentar la incorporació de la llengua anglesa en els Cicles Formatius",
            "inici": "2020-06-17T12:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "LIDIA BARREIRO TABOADA",
            "codirector": "",
            "ponent": "",
            "estudiant": "JOAN SANCHEZ PELLICER"
        },
        {
            "codi": 150574,
            "titol": "Informe sobre els estudis impartits a un centre de formació professional del sector de l'automoció",
            "inici": "2020-06-17T10:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "RAÚL LÓPEZ SÁNCHEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "RAMON BORRÀS CRISTÒFOL"
        },
        {
            "codi": 150593,
            "titol": "Com avaluem la competència personal i social?",
            "inici": "2020-06-17T18:50:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MONTSERRAT PEREZ MOYA",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARTA COROMINAS MARISCOT"
        },
        {
            "codi": 150599,
            "titol": "Les tecnologies de l'aigua com a projecte interdisciplinari a l'ensenyament secundari",
            "inici": "2020-06-17T12:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ESTER GUAUS GUERRERO",
            "codirector": "",
            "ponent": "",
            "estudiant": "NEUS PAGÈS HERNANDO"
        },
        {
            "codi": 150641,
            "titol": "PROJECTE MULTIDISCIPLINARI PER CREAR UN PROCÉS AUTOMATITZAT en GRUPS TREBALLANT DE MANERA COOPERATIVA i COL·LABORATIVA ENTRE ELS ALUMNES DE QUART D'ESO DE SECUNDÀRIA.",
            "inici": "2020-06-17T16:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "DAVID LÓPEZ ÁLVAREZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "MANEL ARRABAL SIERRA"
        },
        {
            "codi": 150555,
            "titol": "Definició i disseny del mòdul Dual pel estudiants de Cicle Formatiu de Grau Superior de Producció Agroecològica que no faran l'estada a l'empresa",
            "inici": "2020-06-17T11:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "IMMA TORRA BITLLOCH",
            "codirector": "",
            "ponent": "",
            "estudiant": "JANIRA ALEMANY SANCHEZ"
        },
        {
            "codi": 150556,
            "titol": "Análisis bibliográfico de la motivación del profesorado y su relación el con rendimiento académico del alumnado de Formación Profesional de Grado Medio (FPGM)",
            "inici": "2020-06-17T17:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ANTONIO CAÑABATE CARMONA",
            "codirector": "",
            "ponent": "",
            "estudiant": "SILVIA PICAZO AGUIRREGABIRIA"
        },
        {
            "codi": 150624,
            "titol": "Aprenentatge basat en problemes a l'aula de tecnologia",
            "inici": "2020-06-17T10:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ROSA PÀMIES VILÀ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ORIOL MONSERDÀ SECURUN"
        },
        {
            "codi": 140397,
            "titol": "Adaptacions didàctiques per a millorar l'aprenentatge dels alumnes amb un pla de suport individualitzat (PI) en activitats gamificades de l'ESO",
            "inici": "2020-06-17T17:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MARTA PEÑA CARRERA",
            "codirector": "",
            "ponent": "",
            "estudiant": "MERITXELL PESQUER RUIZ"
        },
        {
            "codi": 140366,
            "titol": "Aplicació de metodologies actives en el Cicle Formatiu de Grau Superior de Realització Audiovisual",
            "inici": "2020-06-17T17:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "GLADYS MIRIAM UTRERA IGLESIAS",
            "codirector": "",
            "ponent": "",
            "estudiant": "IRENE MUÑOZ LÓPEZ"
        },
        {
            "codi": 150635,
            "titol": "Anàlisi sobre els projectes interdisciplinaris a 3º d'ESO d'un centre de secundària",
            "inici": "2020-06-17T12:50:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "RAMÓN MARTI MARANILLO",
            "codirector": "",
            "ponent": "",
            "estudiant": "DAVID GONZALEZ NAVEROS"
        },
        {
            "codi": 150647,
            "titol": "Aprenentatge basat en problemes (ABP) a 1er d'ESO per fomentar la inclusió i la perspectiva de gènere a l'aula de tecnologia",
            "inici": "2020-06-17T17:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MAICA SANZ GOMEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARC FONT CORNELLÀ"
        },
        {
            "codi": 150577,
            "titol": "Projecte de millora entorn del centre",
            "inici": "2020-06-17T16:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "EVA OLLER IBARS",
            "codirector": "",
            "ponent": "",
            "estudiant": "ALBERT HUALDE GUILLAMET"
        },
        {
            "codi": 150594,
            "titol": "Estratègies docents per a que els alumnes trobin sentit a l'aprenentatge.",
            "inici": "2020-06-17T18:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "GEMMA GARCIA CALATAYUD",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARC EXPÓSITO CUSCO"
        },
        {
            "codi": 140403,
            "titol": "Proyecto interdisciplinar para mejorar la integración de conocimientos para los alumnos de secundaria",
            "inici": "2020-06-17T16:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "JOAN DOMINGO PEÑA",
            "codirector": "",
            "ponent": "",
            "estudiant": "BOUZIANE HRICH MABCHOUR"
        },
        {
            "codi": 150629,
            "titol": "Introducción de los elementos e-textiles en la educación secundaria",
            "inici": "2020-06-17T16:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ORIOL BOIX ARAGONES",
            "codirector": "",
            "ponent": "",
            "estudiant": "ELENA MARIA FREIJO SOBRADO"
        },
        {
            "codi": 150643,
            "titol": "Impuls de l'ús de dispositius mòbils per l'adquisició i millora de competències. Normativa associada",
            "inici": "2020-06-17T18:50:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MONTSERRAT PEREZ MOYA",
            "codirector": "",
            "ponent": "",
            "estudiant": "ARNAU DIAZ MEDEL"
        },
        {
            "codi": 150570,
            "titol": "PROPOSTA D'IMPLANTACIÓ D'UN PUNT D'INFORMACIÓ I PARTICIPACIÓ JUVENIL EN UN CENTRE DE FORMACIÓ PROFESSIONAL",
            "inici": "2020-06-17T18:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "JOAN JOSEP ROA ROVIRA",
            "codirector": "",
            "ponent": "",
            "estudiant": "GUILLEM VENTOSA YUSTE"
        },
        {
            "codi": 150588,
            "titol": "Disseny d'activitats per a despertar l'interès per la tecnologia de les noies de 1r i 2n d'ESO.",
            "inici": "2020-06-17T10:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "M. AMPARO NUÑEZ ANDRES",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARTA VILLACH JORDÀ"
        },
        {
            "codi": 150612,
            "titol": "Desenvolupament d'eines per potenciar els hàbits alimentaris saludables i respectuosos amb el medi en l'alumnat de secundària.",
            "inici": "2020-06-17T12:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "JOSEP FERNÀNDEZ RUZAFA",
            "codirector": "",
            "ponent": "",
            "estudiant": "JOSEP RAMON ESTEVE MAYORAL"
        },
        {
            "codi": 150563,
            "titol": "ATENCIO A LA DIVERSITAT MITJANÇANT LA GAMIFICACIÓ EN FP",
            "inici": "2020-06-17T10:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "JOSEP FERNÀNDEZ RUZAFA",
            "codirector": "",
            "ponent": "",
            "estudiant": "RAMON MUÑOZ CONDE"
        },
        {
            "codi": 150598,
            "titol": "Projecte de quart d'ESO a l'assignatura de Tecnologia. Adquisició i reforma completa d'un habitatge.",
            "inici": "2020-06-17T16:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "M. NÚRIA SALAN BALLESTEROS",
            "codirector": "",
            "ponent": "",
            "estudiant": "LAURA GRIERA I VIDAL"
        },
        {
            "codi": 150642,
            "titol": "Estudi de la implementació de metodologia ludificada com a element motivador a través de la plataforma ClassCraft en una unitat didàctica de Tecnologia",
            "inici": "2020-06-17T10:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ROSA PÀMIES VILÀ",
            "codirector": "",
            "ponent": "",
            "estudiant": "FERRAN ROCA SEBA"
        },
        {
            "codi": 150645,
            "titol": "Tecnoètica a l'Educació Secundària Obligatòria.",
            "inici": "2020-06-17T17:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "ANTONI HERNANDEZ FERNANDEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "EVA RAMIREZ MARQUES"
        },
        {
            "codi": 140384,
            "titol": "Estudio de la conciencia climática y de sostenibilidad en alumnos de 1º ciclo de ESO.",
            "inici": "2020-06-17T12:50:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "NOELIA OLMEDO TORRE",
            "codirector": "",
            "ponent": "",
            "estudiant": "LAURA VILLAESCUSA BLEDA"
        },
        {
            "codi": 140342,
            "titol": "Recondicionament d'equips informàtics com a metodologia d'aprenentatge servei per fomentar la reutilització d'aquests amb finalitat social en el CFGM Sistemes Microinformàtics i Xarxes",
            "inici": "2020-06-17T18:50:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MARIA JOSE CASAÑ GUERRERO",
            "codirector": "",
            "ponent": "",
            "estudiant": "JOSE GARCIA CARBONELL"
        },
        {
            "codi": 140343,
            "titol": "Impacte pedagògic i social de projectes APS a Cicles Formatius de Grau Superior",
            "inici": "2020-06-17T10:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "OSCAR FARRERONS VIDAL",
            "codirector": "",
            "ponent": "",
            "estudiant": "PAULA ADHARA KOBEAGA PI"
        },
        {
            "codi": 140347,
            "titol": "Desenvolupament de material per M7 SMX per a metodologia ABP",
            "inici": "2020-06-17T10:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "RAÚL LÓPEZ SÁNCHEZ",
            "codirector": "IVAN QUERO",
            "ponent": "",
            "estudiant": "EDUARDO TEJERO VILARIÑO"
        },
        {
            "codi": 151036,
            "titol": "Proposta d'implementació del programari 'Processing' a l'assignatura de Tecnologia de l'ESO com a material didàctic de suport.",
            "inici": "2020-06-17T16:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "IGNASI ESQUERRA LLUCIÀ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ADRIÀ BOTAM I CORTINA"
        },
        {
            "codi": 150542,
            "titol": "Les prediccions tecnològiques de la ciència ficció del segle XX com a eina per estimular l'aprenentatge de l'alumnat de formació professional (FP)",
            "inici": "2020-06-17T16:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MANUEL MORENO LUPIAÑEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "PAULA RUBIRALTA PIEROLA"
        },
        {
            "codi": 140615,
            "titol": "Flipped Classroom",
            "inici": "2020-06-17T16:00:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "BEATRIZ OTERO CALVIÑO",
            "codirector": "",
            "ponent": "",
            "estudiant": "JOSEP MARIA BOIX GRAVALOSA"
        },
        {
            "codi": 150650,
            "titol": "Neuroeducació en cicles formatius: Guía pràctica pel professorat",
            "inici": "2020-06-17T12:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MARCEL FERNANDEZ MUÑOZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "BEATRIZ SEVILLA VILLANUEVA"
        },
        {
            "codi": 150637,
            "titol": "Disseny de visites externes al centre per facilitar l'aprenentatge de la tecnologia dels alumnes de secundària d'acord amb el model d'escola oberta.",
            "inici": "2020-06-17T17:10:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "IMMA TORRA BITLLOCH",
            "codirector": "",
            "ponent": "",
            "estudiant": "JORDI GUILANYÀ BORRELLAS"
        },
        {
            "codi": 140368,
            "titol": "Formació emocional i motivació dels alumnes dels Programes de Formació i Inserció (PFI)",
            "inici": "2020-06-17T12:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "JUDITH TELLO ARTIGAS",
            "codirector": "",
            "ponent": "",
            "estudiant": "FRANCESC ORDOÑO ESTEVE"
        },
        {
            "codi": 140378,
            "titol": "APRENDRE I ENSENYAR AMB SISTEMES DE LIVE STREAMING. Investigació de tecnologies i propostes didàctiques adequades al currículum de l'ESO.",
            "inici": "2020-06-17T10:35:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "MIQUEL SORIANO IBAÑEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "JORDI CASANOVAS NORDBECK"
        },
        {
            "codi": 150527,
            "titol": "Desenvolupament de material didàctic per a l'aprenentatge del disseny i creació de sistemes informàtics i electrònics",
            "inici": "2020-06-17T18:50:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "JORDI COSP VILELLA",
            "codirector": "",
            "ponent": "",
            "estudiant": "SANTIAGO RIVAS CONTRERAS"
        },
        {
            "codi": 150622,
            "titol": "Millora de l'adequació d'un institut escola al programa Escoles Verdes. Disseny de projectes per la participació de la comunitat educativa en el funcionament sostenible del centre.",
            "inici": "2020-06-17T18:15:00",
            "lloc": "Google Meet",
            "pla": "MSEC",
            "modalitat": "A",
            "credits": 6,
            "director": "RAFAEL MORILLAS VARON",
            "codirector": "",
            "ponent": "",
            "estudiant": "DAVID SALGADO FUNES"
        },
        {
            "codi": 152034,
            "titol": "Anàlisi de l'assignació de canals en GuifiSants",
            "inici": "2020-06-29T17:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "LLORENÇ CERDÀ ALABERN",
            "codirector": "",
            "ponent": "",
            "estudiant": "JORGE FERRER RODRIGUEZ"
        },
        {
            "codi": 152210,
            "titol": "Identify risk patterns in code commits for test optimization",
            "inici": "2020-06-29T11:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "OSCAR ROMERO MORAL",
            "codirector": "BLADIMIR DE LA HOZ",
            "ponent": "",
            "estudiant": "FERRAN TORRES MORALES"
        },
        {
            "codi": 152718,
            "titol": "Algoritme d'edició de superfícies a temps real",
            "inici": "2020-06-29T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "ANTONIO CHICA CALAF",
            "codirector": "",
            "ponent": "",
            "estudiant": "EDUARD PUJOL PUIG"
        },
        {
            "codi": 152625,
            "titol": "Optimització de funcions d'ona per a l'estat fonamental d'un sistema quàntic de N partícules bosòniques",
            "inici": "2020-06-29T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JOAQUIM CASULLERAS AMBROS",
            "codirector": "FERRAN MAZZANTI CASTRILLEJO",
            "ponent": "",
            "estudiant": "JORDI SALA JUÁREZ"
        },
        {
            "codi": 153037,
            "titol": "Scheduling strategies for time-sensitive distributed applications on edge computing",
            "inici": "2020-06-29T11:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "EDUARDO QUIÑONES MORENO",
            "codirector": "MARIA ASTON SERRANO GRACIA",
            "ponent": "MIQUEL MORETÓ PLANAS",
            "estudiant": "EUDALD SABATÉ CREIXELL"
        },
        {
            "codi": 151988,
            "titol": "Reducció del consum d'energia basat en la simulació de l'ús de diferents solucions constructives i aparells consumidors",
            "inici": "2020-06-29T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSE SOUTO LEON",
            "codirector": "",
            "ponent": "ENRIC MAYOL SARROCA",
            "estudiant": " ALEMANY I VERGÉ"
        },
        {
            "codi": 152585,
            "titol": "A Tool for integrating dynamic healthcare data sources",
            "inici": "2020-06-29T12:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "OSCAR FLORES BAQUERO",
            "codirector": "PETAR JOVANOVIC",
            "ponent": "OSCAR ROMERO MORAL",
            "estudiant": "MEYSAM ZAMANI FOROOSHANI"
        },
        {
            "codi": 153333,
            "titol": "Carbon footprint of companies",
            "inici": "2020-06-29T15:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JOSEP SOLE PARETA",
            "codirector": "",
            "ponent": "",
            "estudiant": "PAU MATEU JORDI"
        },
        {
            "codi": 152734,
            "titol": "An integration data tool for joinable tables based on Apache Spark",
            "inici": "2020-06-29T13:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "SERGI NADAL FRANCESCH",
            "codirector": "OSCAR ROMERO MORAL",
            "ponent": "",
            "estudiant": "JAVIER DE JESÚS FLORES HERRERA"
        },
        {
            "codi": 151824,
            "titol": "Segmentació en VLANS de la xarxa d'una gran empresa",
            "inici": "2020-06-29T15:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JAVIER MONTERO TORRES",
            "codirector": "",
            "ponent": "GERMAN SANTOS BOADA",
            "estudiant": "ANTONI AMATE ORTIZ"
        },
        {
            "codi": 152079,
            "titol": "Diseño e implementación de una infraestructura Big Data en el Cloud",
            "inici": "2020-06-29T16:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "SERGI NADAL FRANCESCH",
            "codirector": "ANTONIA GÓMEZ GONZÁLEZ",
            "ponent": "",
            "estudiant": "MARC CATRISSE PÉREZ"
        },
        {
            "codi": 152406,
            "titol": "Decisió, integració i desplegament d'un nou TMS",
            "inici": "2020-06-29T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "GUILLERMO CEBALLOS",
            "codirector": "",
            "ponent": "ENRIC MAYOL SARROCA",
            "estudiant": "ALEIX ROSELLÓ ROSIÑOL"
        },
        {
            "codi": 153465,
            "titol": "Aplicació d'eines d'anàlisi massiu de dades a l'estudi genètic de malalties complexes",
            "inici": "2020-06-29T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "",
            "codirector": "",
            "ponent": "LUIS ANTONIO BELANCHE MUÑOZ",
            "estudiant": "DAVID SANCHEZ PEÑA"
        },
        {
            "codi": 152864,
            "titol": "Sistema d'identificació del personal i de gestió de la dedicació de les hores de treball en la fabricació de productes electrònics en el sector de l'automoció",
            "inici": "2020-06-29T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JORGE MORALES FERNANDEZ",
            "codirector": "",
            "ponent": "ENRIC MAYOL SARROCA",
            "estudiant": "ENRIC LOPEZ PRAT"
        },
        {
            "codi": 146558,
            "titol": "Anàlisi de riscos a vehicles intel·ligents",
            "inici": "2020-06-29T14:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ANTONIA GÓMEZ GONZÁLEZ",
            "codirector": "",
            "ponent": "MANEL MEDINA LLINÀS",
            "estudiant": "MATIAS EUGENIO ALTAMIRANO SABATO"
        },
        {
            "codi": 152711,
            "titol": "A study of visibility graphs for time series representations",
            "inici": "2020-06-29T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "ARGIMIRO ARRATIA QUESADA",
            "codirector": "",
            "ponent": "",
            "estudiant": "CARLOS BERGILLOS I VARELA"
        },
        {
            "codi": 152576,
            "titol": "Analysis of sensory data using Graph Signal Processing.",
            "inici": "2020-06-29T12:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "JOSE MARIA BARCELÓ ORDINAS",
            "codirector": "JORGE GARCÍA VIDAL",
            "ponent": "",
            "estudiant": "IVAN SALFATI CALLEJA"
        },
        {
            "codi": 154280,
            "titol": "Elaboració d'un sistema networks de Chronojump per a usuari",
            "inici": "2020-06-29T17:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "",
            "codirector": "",
            "ponent": "XAVIER FRANCH GUTIÉRREZ",
            "estudiant": "MAX ROS MOREJON"
        },
        {
            "codi": 152201,
            "titol": "Multilingual Neural Machine Translation: the case-study for Catalan, Spanish and Portuguese Romance Languages",
            "inici": "2020-06-29T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARTA RUIZ COSTA-JUSSA",
            "codirector": "",
            "ponent": "",
            "estudiant": "PERE VERGÉS BONCOMPTE"
        },
        {
            "codi": 154497,
            "titol": "Surffic - Desenvolupament d'una aplicació web per a la gestió de taules de surf",
            "inici": "2020-06-29T16:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MARTI TAPIA PALACIO",
            "codirector": "",
            "ponent": "CARLES FARRE TOST",
            "estudiant": "JORGE MATAS GARCÍA"
        },
        {
            "codi": 153053,
            "titol": "Novel heterogeneous deployment of distributed applications across the compute continuum with COMPSs",
            "inici": "2020-06-30T18:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "EDUARDO QUIÑONES MORENO",
            "codirector": "MARIA ASTON SERRANO GRACIA",
            "ponent": "MIQUEL MORETÓ PLANAS",
            "estudiant": "UNAI PEREZ MENDIZABAL"
        },
        {
            "codi": 152640,
            "titol": "Desenvolupament de tècniques de moviment de personatges virtuals per a corregir la posició física de l'usuari en entorns de RV inmersiva",
            "inici": "2020-06-30T09:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "NURIA PELECHANO GOMEZ",
            "codirector": "ALEJANDRO RÍOS JEREZ",
            "ponent": "",
            "estudiant": "ÓSCAR CURTO CORMENZANA"
        },
        {
            "codi": 153481,
            "titol": "Emotion Recognition in Speech",
            "inici": "2020-06-30T18:00:00",
            "lloc": "Google Meet",
            "pla": "MAI",
            "modalitat": "B",
            "credits": 18,
            "director": "ADIL MOUJAHID",
            "codirector": "",
            "ponent": "LLUIS PADRO CIRERA",
            "estudiant": "MARINA KREPLAK LÓPEZ"
        },
        {
            "codi": 152575,
            "titol": "Non-realistic rendering (hatching)",
            "inici": "2020-06-30T12:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "CARLOS ANDUJAR GRAN",
            "codirector": "",
            "ponent": "",
            "estudiant": "ISADORA SALVETTI ALBRECHT"
        },
        {
            "codi": 152573,
            "titol": "Detection and Segmentation of QR codes with arbitrary deformations",
            "inici": "2020-06-30T17:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "JAVIER RUIZ HIDALGO",
            "codirector": "ISMAEL BENITO ALTAMIRANO",
            "ponent": "OSCAR ROMERO MORAL",
            "estudiant": "HAMID LATIF MARTINEZ"
        },
        {
            "codi": 152733,
            "titol": "Temporal Interpolation of human point clouds using neural networks and body part segmentation",
            "inici": "2020-06-30T11:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "D",
            "credits": 30,
            "director": "IRENE VIOLA",
            "codirector": "PABLO CESAR",
            "ponent": "ANTONIO CHICA CALAF",
            "estudiant": "IGNACIO REIMAT CORBELLA"
        },
        {
            "codi": 153036,
            "titol": "Mobile application for maintenance tasks monitoring",
            "inici": "2020-06-30T13:00:00",
            "lloc": "Google Meet",
            "pla": "MEI",
            "modalitat": "A",
            "credits": 30,
            "director": "PERE PAU VÁZQUEZ ALCOCER",
            "codirector": "",
            "ponent": "",
            "estudiant": "ENRIC GINER LÓPEZ"
        },
        {
            "codi": 154160,
            "titol": "Evaluación y optimización de algoritmos FFT en arquitecturas diversas",
            "inici": "2020-06-30T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "",
            "codirector": "",
            "ponent": "JESUS JOSE LABARTA MANCHO",
            "estudiant": "PABLO VIZCAÍNO SERRANO"
        },
        {
            "codi": 154498,
            "titol": "Extracción de información de sentencias judiciales",
            "inici": "2020-06-30T17:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "LLUIS PADRO CIRERA",
            "codirector": "JOSE CARMONA VARGAS",
            "ponent": "",
            "estudiant": "YIMIN PAN"
        },
        {
            "codi": 153034,
            "titol": "Detection of whales and boats in satellite imagery using CNNs",
            "inici": "2020-06-30T16:00:00",
            "lloc": "Google Meet",
            "pla": "MAI",
            "modalitat": "A",
            "credits": 18,
            "director": "ENRIQUE ROMERO MERINO",
            "codirector": "LUDWIG ROLAND HOUEGNIGAN",
            "ponent": "",
            "estudiant": "DANIELA FURLAN GONZALEZ"
        },
        {
            "codi": 152878,
            "titol": "Instrumentación de OpenACC en Extrae",
            "inici": "2020-06-30T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JUDIT GIMENEZ LUCAS",
            "codirector": "",
            "ponent": "JESUS JOSE LABARTA MANCHO",
            "estudiant": "ALI MUHAMMAD SHIEKH"
        },
        {
            "codi": 152768,
            "titol": "Cómputo y gestión del riesgo de afectación por desastres naturales en el ámbito de los seguros",
            "inici": "2020-06-30T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSE LUIS SANCHEZ",
            "codirector": "",
            "ponent": "MARIA JOSEP BLESA AGUILERA",
            "estudiant": "VÍCTOR VALLEJO RIVES"
        },
        {
            "codi": 153130,
            "titol": "Adaptabilitat d'interfícies d'usuari gràfiques per a diferents dispositius",
            "inici": "2020-06-30T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARTA FAIREN GONZALEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "JAUME PUIG I TURÓN"
        },
        {
            "codi": 154982,
            "titol": "Identify cybersecurity threats from web browsing logs by using Machine Learning and Artificial Intelligence",
            "inici": "2020-06-30T19:00:00",
            "lloc": "Google Meet",
            "pla": "MAI",
            "modalitat": "A",
            "credits": 18,
            "director": "JAVIER BÉJAR ALONSO",
            "codirector": "",
            "ponent": "",
            "estudiant": "EMER RODRIGUEZ FORMISANO"
        },
        {
            "codi": 152791,
            "titol": "Disseny i implementació d'un Open Data Catalog per a la gestió i prevenció de riscos associats a desastres naturals",
            "inici": "2020-06-30T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSE LUIS SANCHEZ ROS",
            "codirector": "",
            "ponent": "CARME QUER BOSOR",
            "estudiant": "CARLOS AIRES ESPEJO"
        },
        {
            "codi": 152174,
            "titol": "Aplicatiu de Creació Automàtica de Planificacions d'Entrenament Personalitzat",
            "inici": "2020-06-30T18:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSÉ MARÍA RODRÍGUEZ VALLS",
            "codirector": "",
            "ponent": "ENRIQUE ROMERO MERINO",
            "estudiant": "ROGER ALMATÓ BAUCELLS"
        },
        {
            "codi": 151878,
            "titol": "Refactorización de una aplicación a través de un desarrollo guiado por test",
            "inici": "2020-06-30T09:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "VICTOR MOLEIRO",
            "codirector": "",
            "ponent": "JORDI DELGADO PIN",
            "estudiant": "ÁLVARO LUQUE VARGAS"
        },
        {
            "codi": 147842,
            "titol": "Visual analysis of weather forecast data",
            "inici": "2020-06-30T12:00:00",
            "lloc": "Google Meet",
            "pla": "MEI",
            "modalitat": "A",
            "credits": 30,
            "director": "PERE PAU VÁZQUEZ ALCOCER",
            "codirector": "",
            "ponent": "",
            "estudiant": "ROBERT POLAT CARAUSU"
        },
        {
            "codi": 153179,
            "titol": "Midas (Web App)",
            "inici": "2020-06-30T16:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOAN VENDRELL",
            "codirector": "",
            "ponent": "ERNEST TENIENTE LOPEZ",
            "estudiant": "AGUSTÍ SALAMERO VILARÓ"
        },
        {
            "codi": 139981,
            "titol": "A4CAT. A Plataform for Weather-Related Risk Events Management",
            "inici": "2020-06-30T15:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "RAFAEL SÁNCHEZ DIEZMA GUIJARRO",
            "codirector": "",
            "ponent": "JOSE LUIS BALCÁZAR NAVARRO",
            "estudiant": "ADNAN BOOTA"
        },
        {
            "codi": 150683,
            "titol": "Desenvolupament d'una interfície gràfica web per un model d'optimització",
            "inici": "2020-06-30T15:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JAUME FIGUERAS JOVE",
            "codirector": "",
            "ponent": "MARIA PAZ LINARES HERREROS",
            "estudiant": "VICTOR TOMAS RODRIGUEZ"
        },
        {
            "codi": 152080,
            "titol": "Integración de software contenerizado en COMPSs",
            "inici": "2020-06-30T16:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "ROSA MARIA BADIA SALA",
            "codirector": "JORGE EJARQUE ARTIGAS",
            "ponent": "",
            "estudiant": "CARLOS SANTIAGO ALVARADO AGUILERA"
        },
        {
            "codi": 151638,
            "titol": "\"Design and implementation of a DevOps(CI/CD) system for multi language open source projects",
            "inici": "2020-06-30T15:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "ROSA MARIA BADIA SALA",
            "codirector": "EJARQUE ARTIGAS, JORGE",
            "ponent": "",
            "estudiant": "SERGI MARTÍNEZ RODRÍGUEZ"
        },
        {
            "codi": 153178,
            "titol": "Desenvolupament d'una SPA per a un Servei Municipl",
            "inici": "2020-06-30T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MARIÀ CAMÚÑEZ LUENGO",
            "codirector": "",
            "ponent": "XAVIER BURGUÉS ILLA",
            "estudiant": "MARC SOLER ARAGUÁS"
        },
        {
            "codi": 153050,
            "titol": "Improving comunication in task-based runtimes for heterogeneous systems",
            "inici": "2020-06-30T17:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "CARLOS ALVAREZ MARTINEZ",
            "codirector": "DANIEL JIMENEZ GONZALEZ",
            "ponent": "",
            "estudiant": "RUBÉN CANO DÍAZ"
        },
        {
            "codi": 152578,
            "titol": "Compressed Representation of 3D Models for 3D Printing",
            "inici": "2020-06-30T10:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "ANTONIO CHICA CALAF",
            "codirector": "",
            "ponent": "",
            "estudiant": "JOÃO HUGO BALLESTEROS BRANDÃO"
        },
        {
            "codi": 148689,
            "titol": "Reinforcement Learning applied to MMORPG",
            "inici": "2020-06-30T17:00:00",
            "lloc": "Google Meet",
            "pla": "MAI",
            "modalitat": "A",
            "credits": 18,
            "director": "MARIO MARTÍN MUÑOZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "CARLOS ALEJANDRO GONCEVATT"
        },
        {
            "codi": 153043,
            "titol": "Sequence-Aware Pairing in the AURIX TC297XT Multicore Processor for the Automotive Domain",
            "inici": "2020-06-30T15:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "ENRICO MEZZETTI",
            "codirector": "FRANCISCO JAVIER CAZORLA ALMEIDA",
            "ponent": "LEONIDAS KOSMIDIS",
            "estudiant": "JEREMY JENS GIESEN LEÓN"
        },
        {
            "codi": 153044,
            "titol": "Design and implementation of an architecture-aware hardware runtime for heterogeneous systems",
            "inici": "2020-06-30T16:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "CARLOS ALVAREZ MARTINEZ",
            "codirector": "DANIEL JIMENEZ GONZALEZ",
            "ponent": "",
            "estudiant": "JUAN MIGUEL DE HARO RUIZ"
        },
        {
            "codi": 152555,
            "titol": "Desenvolupament d'un sistema de diàleg parlat (chatbot) geriàtric",
            "inici": "2020-06-30T16:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "LLUIS PADRO CIRERA",
            "codirector": "",
            "ponent": "",
            "estudiant": "ORIOL ARANDA LLORENS"
        },
        {
            "codi": 152763,
            "titol": "Mòdul de correcció distribuït per a Jutge.org",
            "inici": "2020-06-30T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JORDI PETIT SILVESTRE",
            "codirector": "",
            "ponent": "",
            "estudiant": "ALEJANDRO ADÁN NAVARRO"
        },
        {
            "codi": 147841,
            "titol": "Creating a Model for Expected Goals in Football using Qualitative Player Information",
            "inici": "2020-06-30T16:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "JAVIER FERNÁNDEZ",
            "codirector": "",
            "ponent": "MARTA ARIAS VICENTE",
            "estudiant": "PAU MADRERO PARDO"
        },
        {
            "codi": 151770,
            "titol": "Especificació i disseny d'un sistema software per a la realització d'auditories de sistemes d'informació",
            "inici": "2020-06-30T17:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ANDREA MARIA BIACHINMANO",
            "codirector": "",
            "ponent": "JOAN ANTONI PASTOR COLLADO",
            "estudiant": "ELOI ROCA CORCELLES"
        },
        {
            "codi": 152148,
            "titol": "Learning Process Models from Images",
            "inici": "2020-06-30T15:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JOSE CARMONA VARGAS",
            "codirector": "ENRIQUE ROMERO MERINO",
            "ponent": "",
            "estudiant": "ALEIX DALMAU I AMEZUA"
        },
        {
            "codi": 152863,
            "titol": "Machine Learning: analysis, optimizations and evaluation of modern frameworks on HPC clusters",
            "inici": "2020-06-30T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "FILIPPO MANTOVANI",
            "codirector": "MARTA GARCIA GASULLA",
            "ponent": "JESUS JOSE LABARTA MANCHO",
            "estudiant": "GUILLEM RAMÍREZ GARGALLO"
        },
        {
            "codi": 152899,
            "titol": "Verychic Back Office",
            "inici": "2020-06-30T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "SERGIO VICO MARFIL",
            "codirector": "",
            "ponent": "CARME QUER BOSOR",
            "estudiant": "ANTONIO GUILERA DOMINGO"
        },
        {
            "codi": 154539,
            "titol": "Desarrollo de aplicaciones utilizando arquitecturas de nueva generación, JAngular, Microservicios...",
            "inici": "2020-06-30T18:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "",
            "codirector": "",
            "ponent": "ERNEST TENIENTE LOPEZ",
            "estudiant": "AGUSTIN D'ACUNTO"
        },
        {
            "codi": 151876,
            "titol": "Building a payment card skimmer database",
            "inici": "2020-06-30T17:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "D",
            "credits": 18,
            "director": "NOLEN SCAIFE",
            "codirector": "",
            "ponent": "ERNEST TENIENTE LOPEZ",
            "estudiant": "ARNAU BUCH TORRENTS"
        },
        {
            "codi": 152507,
            "titol": "Redisseny i nova implementació d'una aplicació de gestió de dades de pacients, familiars i mostes de material genètic",
            "inici": "2020-06-30T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARIA JOSE CASAÑ GUERRERO",
            "codirector": "PYBUS OLIVERAS, MARC",
            "ponent": "",
            "estudiant": "HÉCTOR BAIGES SÁNCHEZ"
        },
        {
            "codi": 151640,
            "titol": "HPC applications for data-driven agent-based  models of pedestrian movement",
            "inici": "2020-06-30T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "DIVI CUESTA, CARLA",
            "codirector": "ROMANOWKSKA, IZA",
            "ponent": "JOSEP CASANOVAS GARCIA",
            "estudiant": "QUIM LÁZARO GEL"
        },
        {
            "codi": 151219,
            "titol": "Implantació d'un sistema de gestió de logs en els Serveis TIC de Camins",
            "inici": "2020-06-30T09:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSEP MARIA JORDANA",
            "codirector": "",
            "ponent": "DAVIDE CAREGLIO",
            "estudiant": "EDUARD OROZCO ALCARRIA"
        },
        {
            "codi": 152879,
            "titol": "Paralelización automática del proceso de aprendizaje de una red neuronal Deep Learning",
            "inici": "2020-06-30T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JORDI TORRES VIÑALS",
            "codirector": "JUAN LUÍS DOMINGUEZ",
            "ponent": "",
            "estudiant": "RAÚL GARCÍA FUENTES"
        },
        {
            "codi": 153040,
            "titol": "On the analysis of hardware event monitors accuracy in MPSoCs for real-time computing systems",
            "inici": "2020-06-30T14:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "HAMID TABANI",
            "codirector": "FRANCISCO JAVIER CAZORLA ALMEIDA",
            "ponent": "LEONIDAS KOSMIDIS",
            "estudiant": "JAVIER ENRIQUE BARRERA HERRERA"
        },
        {
            "codi": 151182,
            "titol": "Can I - Detecta si un alimento es apto para tí",
            "inici": "2020-07-01T09:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "ENRIC MAYOL SARROCA",
            "codirector": "",
            "ponent": "",
            "estudiant": "JAVIER PÉREZ PÉREZ"
        },
        {
            "codi": 148691,
            "titol": "Deep Regression of Social Signals in Dyadic Scenarios",
            "inici": "2020-07-01T16:00:00",
            "lloc": "Google Meet",
            "pla": "MAI",
            "modalitat": "A",
            "credits": 18,
            "director": "SERGIO ESCALERA GUERRERO",
            "codirector": "JULIO JACQUES",
            "ponent": "LUIS ANTONIO BELANCHE MUÑOZ",
            "estudiant": "ITALO ELIZARDO ISAAC VIDAL LUCERO"
        },
        {
            "codi": 152149,
            "titol": "Desarrollo de un módulo de gestión de un E-Commerce/Market Place con Odoo",
            "inici": "2020-07-01T12:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "LUIS MERA CASTELLON",
            "codirector": "",
            "ponent": "DOLORS COSTAL COSTA",
            "estudiant": "JONATAN BERNAL GONZÁLEZ"
        },
        {
            "codi": 154726,
            "titol": "Disseny d'una aplicació web Wordpress/PHP d'una editorial de llibres",
            "inici": "2020-07-01T10:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "CARME MARTIN ESCOFET",
            "codirector": "",
            "ponent": "",
            "estudiant": "ARNAU ORRIOLS GARCIA"
        },
        {
            "codi": 153054,
            "titol": "The High Performance Scheduler Game: A Characterization of Slurm, Metrics, and the Viability of Cooperation.",
            "inici": "2020-07-01T09:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "MARIA JOSE SERNA IGLESIAS",
            "codirector": "",
            "ponent": "",
            "estudiant": "WILMER VIDAL URUCHI TICONA"
        },
        {
            "codi": 152732,
            "titol": "Predictive techniques to support the adjudication of construction works",
            "inici": "2020-07-01T10:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "JOAN PESET IRIBARREN",
            "codirector": "",
            "ponent": "JOSE CARMONA VARGAS",
            "estudiant": "GUILLERMO LAHUERTA PIÑEIRO"
        },
        {
            "codi": 148185,
            "titol": "Apliació Web per gestionar i coordinar una Festa Major",
            "inici": "2020-07-01T11:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "XAVIER BURGUÉS ILLA",
            "codirector": "",
            "ponent": "",
            "estudiant": "SERGI VENTURA SOLSONA"
        },
        {
            "codi": 153257,
            "titol": "Desarrollo de una intranet para la compartición de conocimiento entre empleados",
            "inici": "2020-07-01T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "GABRIEL ANGLADA GARCIA",
            "codirector": "",
            "ponent": "CLAUDIA PATRICIA AYALA MARTINEZ",
            "estudiant": "ROGER GUASCH IBARRA"
        },
        {
            "codi": 152091,
            "titol": "Framework for fast prototyping of Graph Neural Networks",
            "inici": "2020-07-01T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "PERE BARLET ROS",
            "codirector": "ALBERTO CABELLOS APARICIO",
            "ponent": "",
            "estudiant": "DAVID PUJOL PERICH"
        },
        {
            "codi": 151994,
            "titol": "Reducción de la huella de carbono y certificación ambiental en un proyecto constructivo",
            "inici": "2020-07-01T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSE SOUTO LEON",
            "codirector": "",
            "ponent": "CLAUDIA PATRICIA AYALA MARTINEZ",
            "estudiant": "SOULAIMAN EL HAMRI"
        },
        {
            "codi": 152200,
            "titol": "Development of a Data Analysis Application for Improved Code Sustainability",
            "inici": "2020-07-01T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "GABRIEL CRUZ",
            "codirector": "",
            "ponent": "JORDI MONTERO GARCIA",
            "estudiant": "ANDREU ESTERAS CASASOLA"
        },
        {
            "codi": 154360,
            "titol": "Anàlisi i disseny del nou Sistema d'Informes d'Actuació i d'Intervenció dels Bombers de Barcelona",
            "inici": "2020-07-01T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSEP CLOTET CIRUELO",
            "codirector": "",
            "ponent": "JOAN ANTONI PASTOR COLLADO",
            "estudiant": "JOSEP CORDON PUIG"
        },
        {
            "codi": 151858,
            "titol": "Applet of geometric algorithms",
            "inici": "2020-07-01T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "VERA SACRISTAN ADINOLFI",
            "codirector": "",
            "ponent": "",
            "estudiant": "CARLOS BAYONA PEINADO"
        },
        {
            "codi": 152033,
            "titol": "Redeptiom Rates Revamp: Managing multiple rates in a single reservation",
            "inici": "2020-07-01T09:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "TERESA FINEZ MORAL",
            "codirector": "",
            "ponent": "CARME MARTIN ESCOFET",
            "estudiant": "POL GIL HERNÁNDEZ"
        },
        {
            "codi": 152516,
            "titol": "Watermark removal using Deep Learning",
            "inici": "2020-07-01T11:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ANGEL ESTABAN SOTO",
            "codirector": "",
            "ponent": "JAVIER BÉJAR ALONSO",
            "estudiant": "ADRIÀ CABEZA SANT'ANNA"
        },
        {
            "codi": 151046,
            "titol": "Image Recognition in Fashion Retail",
            "inici": "2020-07-01T09:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOAN VENDRELL",
            "codirector": "DAVID BOFILL",
            "ponent": "JAVIER BÉJAR ALONSO",
            "estudiant": "ALBERTO GIMÉNEZ ARAGÓN"
        },
        {
            "codi": 152081,
            "titol": "Desenvolupament i aplicació de Microfrontends",
            "inici": "2020-07-01T11:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ROBERTO GRASSI",
            "codirector": "",
            "ponent": "DOLORS COSTAL COSTA",
            "estudiant": "SERGI SERRANO CASALINS"
        },
        {
            "codi": 153041,
            "titol": "Speeding up Document Image Classification",
            "inici": "2020-07-01T11:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "JORDI TORRES VIÑALS",
            "codirector": "",
            "ponent": "",
            "estudiant": "JAVIER FERRANDO MONSONÍS"
        },
        {
            "codi": 152820,
            "titol": "Elaboració d'un pla estratègic de sistemes d'informació d'una empresa d'equips de protecció individual",
            "inici": "2020-07-01T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JAVIER MARTIN RODRÍGUEZ",
            "codirector": "",
            "ponent": "ENRIC MAYOL SARROCA",
            "estudiant": "OMAR ANGUERA ALEGRE"
        },
        {
            "codi": 152584,
            "titol": "Unleashing Robotic Process Automation Through Process Mining",
            "inici": "2020-07-01T09:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "JOSE CARMONA VARGAS",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARIA GKOTSOPOULOU"
        },
        {
            "codi": 152011,
            "titol": "Sistema Recomanador de productes d'hosteleria",
            "inici": "2020-07-01T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "RAQUEL FERNANDEZ MONTENEGRO",
            "codirector": "ALBERT CALVO IBAÑEZ",
            "ponent": "LIDIA MONTERO MERCADÉ",
            "estudiant": "POL RENAU LARRODÉ"
        },
        {
            "codi": 149276,
            "titol": "Training strategies for an European Distributed Deep Learning Library (EDDLL)",
            "inici": "2020-07-01T15:00:00",
            "lloc": "Google Meet",
            "pla": "MAI",
            "modalitat": "B",
            "credits": 18,
            "director": "EDUARDO QUIÑONES MORENO",
            "codirector": "",
            "ponent": "DARIO GARCÍA GASULLA",
            "estudiant": "JESÚS PERALES HERNÁNDEZ"
        },
        {
            "codi": 151800,
            "titol": "Implantació d'una metodologia per a la gestió de projectes",
            "inici": "2020-07-01T10:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "LUIS MERA CASTELLÓN",
            "codirector": "",
            "ponent": "ENRIC MAYOL SARROCA",
            "estudiant": "JORDI FERNÁNDEZ CUEVAS"
        },
        {
            "codi": 145847,
            "titol": "Patrons de disseny per a microserveis",
            "inici": "2020-07-01T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "CARLES FARRE TOST",
            "codirector": "",
            "ponent": "",
            "estudiant": "ROGER ORIOL PÉREZ"
        },
        {
            "codi": 146299,
            "titol": "Generador d'horaris",
            "inici": "2020-07-01T12:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "M. LUISA BONET CARBONELL",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARTÍ ROSELL OLLÉ"
        },
        {
            "codi": 153049,
            "titol": "Generating and Exploiting Deep Learning Variants to Increase Utilization of the Heterogeneous Resources in Autonomous Driving Platforms",
            "inici": "2020-07-01T11:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "HAMID TABANI",
            "codirector": "FRANCISCO JAVIER CAZORLA ALMEIDA",
            "ponent": "LEONIDAS KOSMIDIS",
            "estudiant": "ROGER PUJOL TORRAMORELL"
        },
        {
            "codi": 152582,
            "titol": "New Innovations in eIDAS-compliant Trust Services: Anomally detection using AI/ML",
            "inici": "2020-07-01T11:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "FRANCISCO JORDAN FERNÁNDEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARC MÉNDEZ ROCA"
        },
        {
            "codi": 148703,
            "titol": "Request recommender with the use of deep learning for text classification",
            "inici": "2020-07-01T17:00:00",
            "lloc": "Google Meet",
            "pla": "MAI",
            "modalitat": "B",
            "credits": 18,
            "director": "XAVIER NOGUERA PAGÈS",
            "codirector": "",
            "ponent": "ULISES CORTÉS GARCÍA",
            "estudiant": "RAQUEL NICOLAU VIDAL"
        },
        {
            "codi": 151931,
            "titol": "Deep learning applied to people detection, tracking and identification in video",
            "inici": "2020-07-01T10:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JAVIER CASTAN",
            "codirector": "",
            "ponent": "JAVIER BÉJAR ALONSO",
            "estudiant": "ALEX INIESTA GARCIA"
        },
        {
            "codi": 153353,
            "titol": "Anàlisi i optimització del procés de reporting financer i operatiu de principals competidors d'aerolínies low cost.",
            "inici": "2020-07-01T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MARIE CHARLOTTE GUILLEMETTE JEANSON",
            "codirector": "ALEJANDRO LAQUENTE MAS",
            "ponent": "JOAN ANTONI PASTOR COLLADO",
            "estudiant": "SAÜL ABAD COPOVÍ"
        },
        {
            "codi": 153048,
            "titol": "Wind pattern analysis applied to coastal areas",
            "inici": "2020-07-01T10:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "ALICIA AGENO PULIDO",
            "codirector": "",
            "ponent": "",
            "estudiant": "MOUAD MOUSSABBIH"
        },
        {
            "codi": 153046,
            "titol": "Defeating Barriers for Resource Usage Testing for Autonomous Driving Frameworks",
            "inici": "2020-07-01T10:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "HAMID TABANI",
            "codirector": "JAIME ABELLA FERRER",
            "ponent": "MIQUEL MORETÓ PLANAS",
            "estudiant": "MIGUEL ALCÓN DOGANOC"
        },
        {
            "codi": 152730,
            "titol": "Methods and measurements for evaluating HPC systems",
            "inici": "2020-07-02T17:15:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "FILIPPO MANTOVANI",
            "codirector": "MARTA GARCIA GASULLA",
            "ponent": "JESUS JOSE LABARTA MANCHO",
            "estudiant": "FABIO BANCHELLI GRACIA"
        },
        {
            "codi": 152767,
            "titol": "Automatización de la gestión de incidentes de seguridad para incrementar el rendimiento de un SOC",
            "inici": "2020-07-02T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "OSCAR LOPEZ SANTIN",
            "codirector": "CRISTINA DE SAINT GERMAIN CANALES",
            "ponent": "ANTONI URPI TUBELLA",
            "estudiant": "MIGUEL FERNÁNDEZ MARTÍNEZ"
        },
        {
            "codi": 152766,
            "titol": "Reconeixement i categorització de productes al dispositiu amb TensorFlow.js",
            "inici": "2020-07-02T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "GINES ORTIZ",
            "codirector": "",
            "ponent": "ANTONI URPI TUBELLA",
            "estudiant": "MARC GARCIA-PENCHE GRANADOS"
        },
        {
            "codi": 151993,
            "titol": "Implementació d'un processador RISC-V a una FPGA",
            "inici": "2020-07-02T18:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JOSE M. LLABERIA GRIÑÓ",
            "codirector": "JOSEP-LLORENÇ CRUZ DIAZ",
            "ponent": "",
            "estudiant": "GERARD CANDÓN ARENAS"
        },
        {
            "codi": 153027,
            "titol": "Massive data processing for data analysis and visualization to understand sector trend and monitor sales",
            "inici": "2020-07-02T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "D",
            "credits": 18,
            "director": "CHARLES TANDONNET",
            "codirector": "",
            "ponent": "MARTA ARIAS VICENTE",
            "estudiant": "PAUL GAZEL-ANTHOINE"
        },
        {
            "codi": 152252,
            "titol": "Desenvolupament d'aplicació Android per a un reward system per a les cafeteres Nespresso.",
            "inici": "2020-07-02T16:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ANA MARTÍNEZ AZNAREZ",
            "codirector": "",
            "ponent": "PERE PAU VÁZQUEZ ALCOCER",
            "estudiant": "DANIEL GALLARDO AMORES"
        },
        {
            "codi": 152253,
            "titol": "Components Reutilizables amb AEM (Adobe Experience Manager)",
            "inici": "2020-07-02T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "PATRICIA PICANYOL MERCADAL",
            "codirector": "JOSE HUMBERTO MARQUEZ ZAMBRANO           ",
            "ponent": "RUBEN TOUS LIESA",
            "estudiant": "ALEIX COSTA RECTO"
        },
        {
            "codi": 152194,
            "titol": "Desenvolupament mòdul monitorització xatkit",
            "inici": "2020-07-02T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JORDI CABOT SAGRERA",
            "codirector": "",
            "ponent": "RUBEN TOUS LIESA",
            "estudiant": "LLUÍS MARQUÈS PEÑARANDA"
        },
        {
            "codi": 147866,
            "titol": "Visualització avançada de models mèdics",
            "inici": "2020-07-02T15:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "PERE PAU VÁZQUEZ ALCOCER",
            "codirector": "EVA MONCLUS LAHOYA",
            "ponent": "",
            "estudiant": "JOSEP CIURANA HERRERA"
        },
        {
            "codi": 151802,
            "titol": "Implementació d'integració i entrega contínua per a una aplicació web",
            "inici": "2020-07-02T17:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "GERARD VILAPRINYÓ",
            "codirector": "",
            "ponent": "JUAN JOSE COSTA PRATS",
            "estudiant": "GENÍS BOSCH POU"
        },
        {
            "codi": 152251,
            "titol": "Detecció i monitoratge no invasius de la freqüència cardíaca mitjançant visió per computador.",
            "inici": "2020-07-02T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JOAN CLIMENT VILARÓ",
            "codirector": "",
            "ponent": "",
            "estudiant": "GERARD HEREDIA SOLER"
        },
        {
            "codi": 152258,
            "titol": "Optimització del transport dels Centres d'Educació Especial de Barcelona",
            "inici": "2020-07-02T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MARIA PAZ LINARES HERREROS",
            "codirector": "",
            "ponent": "JOSEP CASANOVAS GARCIA",
            "estudiant": "VICTOR DIVÍ CUESTA"
        },
        {
            "codi": 153047,
            "titol": "Network Modeling using Graph Neural Networks",
            "inici": "2020-07-02T11:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "ALBERTO CABELLOS APARICIO",
            "codirector": "PERE BARLET ROS",
            "ponent": "",
            "estudiant": "MIQUEL FERRIOL GALMÉS"
        },
        {
            "codi": 152574,
            "titol": "User Behavioral Segmentation Based on Math Input",
            "inici": "2020-07-02T10:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "DANIEL MARTÍN-ALBO SIMÓN",
            "codirector": "",
            "ponent": "LIDIA MONTERO MERCADÉ",
            "estudiant": "HENRY QIU LO"
        },
        {
            "codi": 152705,
            "titol": "Desarrollo de Aplicaciones utilizando arquitecturas de nueva generación",
            "inici": "2020-07-02T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MONICA RAQUEL HERRERA JIMENEZ",
            "codirector": "",
            "ponent": "FATOS XHAFA XHAFA",
            "estudiant": "MIGUEL SALAMERO MUÑOZ"
        },
        {
            "codi": 152871,
            "titol": "College grades manager and speculator progressive web app",
            "inici": "2020-07-02T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "CRISTINA GÓMEZ SEOANE",
            "codirector": "",
            "ponent": "",
            "estudiant": "MAURICI ABAD GUTIERREZ"
        },
        {
            "codi": 152880,
            "titol": "Automatic organizing of user travel items",
            "inici": "2020-07-02T09:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSEP CUGAT",
            "codirector": "",
            "ponent": "MARTA ARIAS VICENTE",
            "estudiant": "BERNAT TORRES BELLIDO"
        },
        {
            "codi": 153045,
            "titol": "Containers in HPC: Is it worth it?",
            "inici": "2020-07-02T14:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "FILIPPO MANTOVANI",
            "codirector": "MARTA GARCIA GASULLA",
            "ponent": "EDUARD AYGUADÉ PARRA",
            "estudiant": "KILIAN PEIRO CONDE"
        },
        {
            "codi": 152580,
            "titol": "State of the art and characterization of Graph Neural Networks",
            "inici": "2020-07-02T12:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "SERGI ABADAL CAVALLÉ",
            "codirector": "ALBERTO CABELLOS APARICIO",
            "ponent": "",
            "estudiant": "JORGE LÓPEZ ALONSO"
        },
        {
            "codi": 151374,
            "titol": "Mejoras en la búsqueda de caminos punto a punto en el software Aimsun Next mediante métodos heurísticos",
            "inici": "2020-07-02T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "SARA PARDO FERNANDEZ",
            "codirector": "SERGIO MARTÍNEZ LÓPEZ",
            "ponent": "EMMA ROLLÓN RICO",
            "estudiant": "ANTONIO JOSÉ CABRERA VALENZUELA"
        },
        {
            "codi": 152551,
            "titol": "Understanding Literal Block Distance in SAT solvers",
            "inici": "2020-07-02T15:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "ROBERT LUKAS MARIO NIEUWENHUIS",
            "codirector": "ALBERT OLIVERAS LLUNELL",
            "ponent": "",
            "estudiant": "ADRIAN LOZANO NAVARRO"
        },
        {
            "codi": 154353,
            "titol": "A network algorithm for exact tests for Hardy-Weinberg equilibrium with X-chromosomal variants",
            "inici": "2020-07-02T09:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "JAN GRAFFELMAN",
            "codirector": "",
            "ponent": "",
            "estudiant": "LEONARDO ORTOLEVA"
        },
        {
            "codi": 152581,
            "titol": "Molecular Visualization in Virtual Reality",
            "inici": "2020-07-02T10:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "PERE PAU VÁZQUEZ ALCOCER",
            "codirector": "",
            "ponent": "",
            "estudiant": "KONSTANTINOS KAZATZIS"
        },
        {
            "codi": 152821,
            "titol": "Development of a Data Migration Automation Tool From Salesforce To Salesforce",
            "inici": "2020-07-02T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ALICIA GARCÍA ROMERO",
            "codirector": "ALBERTO OTERO PASCUAL",
            "ponent": "CRISTINA GÓMEZ SEOANE",
            "estudiant": "MEIR CARLOS MOUYAL AMSELEM"
        },
        {
            "codi": 153030,
            "titol": "Techniques for reducing and bounding OpenMP dynamic memory",
            "inici": "2020-07-02T15:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "SARA ROYUELA ALCÁZAR",
            "codirector": "EDUARDO QUIÑONES",
            "ponent": "XAVIER MARTORELL BOFILL",
            "estudiant": "ADRIÁN MUNERA SÁNCHEZ"
        },
        {
            "codi": 152881,
            "titol": "Síntesi d'animacions amb físiques i recuperació de l'equilibri",
            "inici": "2020-07-02T18:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "NURIA PELECHANO GOMEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ALBERT ORTIZ GUILLEM"
        },
        {
            "codi": 151801,
            "titol": "Remote Provisioning Architecture for Embedded UICC v4.0 Implementation",
            "inici": "2020-07-02T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "RAUL LORENTE TEJADA",
            "codirector": "",
            "ponent": "JORDI PETIT SILVESTRE",
            "estudiant": "FARNERS VALLESPI SORO"
        },
        {
            "codi": 152707,
            "titol": "Mejora del aplicativo web de una entidad bancaria usando diversas tecnologías relacionadas con Java",
            "inici": "2020-07-02T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MONICA RAQUEL HERRERA JIMENEZ",
            "codirector": "",
            "ponent": "JAIME M. DELGADO MERCE",
            "estudiant": "YUN WU XU"
        },
        {
            "codi": 154499,
            "titol": "Algoritmos Scala para diversas utilidades de negocio",
            "inici": "2020-07-02T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "",
            "codirector": "",
            "ponent": "FATOS XHAFA XHAFA",
            "estudiant": "ERIC MARTIN OBISPO"
        },
        {
            "codi": 152553,
            "titol": "Sistema de predicció de tir en l'entorn de la NBA",
            "inici": "2020-07-02T16:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MIQUEL SANCHEZ MARRE",
            "codirector": "",
            "ponent": "",
            "estudiant": "JORDI VILAJOSANA I RODRIGUEZ"
        },
        {
            "codi": 152902,
            "titol": "Habilitació d'un entorn de preproducció i desenvolupament d'evolutius d'un portal de gestió de certificats digitals.",
            "inici": "2020-07-02T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MARC ARDERIUS",
            "codirector": "",
            "ponent": "DAVIDE CAREGLIO",
            "estudiant": "ISMAEL DOUHA PRIETO"
        },
        {
            "codi": 151992,
            "titol": "Automatizació i millora dels procediments de desplegament d'un producte al Cloud",
            "inici": "2020-07-02T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "MARC MARTI",
            "codirector": "",
            "ponent": "FRANCISCO JORDAN FERNÁNDEZ",
            "estudiant": "ADRIÀ ALCARAZ NUÑEZ"
        },
        {
            "codi": 152083,
            "titol": "New Innovations in eIDAS-compliant Trust Services: Blockchain",
            "inici": "2020-07-02T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "FRANCISCO JORDAN",
            "codirector": "",
            "ponent": "FRANCISCO JORDAN FERNÁNDEZ",
            "estudiant": "XIAOLEI LIN"
        },
        {
            "codi": 152708,
            "titol": "Seguretat en Docker: Anàlisi i protecció de vulnerabilitats",
            "inici": "2020-07-02T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JAIME M. DELGADO MERCE",
            "codirector": "",
            "ponent": "",
            "estudiant": "ORIOL NIN RAMÍREZ"
        },
        {
            "codi": 152032,
            "titol": "Gestión de límites de energía globales para centros HPC",
            "inici": "2020-07-02T19:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JULITA CORBALAN GONZALEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "AURORA TOMÁS BERJAGA"
        },
        {
            "codi": 154840,
            "titol": "An application of explainability methods in reinforcement learning",
            "inici": "2020-07-02T17:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "SERGIO ÁLVAREZ NAPAGAO",
            "codirector": "DMITRY GNATYSHAK",
            "ponent": "",
            "estudiant": "ANTONI CLIMENT MUÑOZ"
        },
        {
            "codi": 152209,
            "titol": "A Virtual Reality visualization of the biosonar communication channel for live in the depths of the sea",
            "inici": "2020-07-02T11:00:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "ANTONIO SUSIN SANCHEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ALBERT GIL SAAVEDRA"
        },
        {
            "codi": 151930,
            "titol": "Estudio y evaluación de técnicas de navegación para Realidad Virtual colaborativa",
            "inici": "2020-07-02T17:30:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "NURIA PELECHANO GOMEZ",
            "codirector": "CARLOS ANDUJAR GRAN",
            "ponent": "",
            "estudiant": "JOSE LUIS PONTON MARTINEZ"
        },
        {
            "codi": 152086,
            "titol": "Segmentació d'imatges usant  transformades de distancia",
            "inici": "2020-07-02T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JOAN CLIMENT VILARÓ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ELOI SEVILLA LÓPEZ"
        },
        {
            "codi": 153314,
            "titol": "Plataforma pel desenvolupament d'experiències PRL en Unity",
            "inici": "2020-07-02T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "",
            "codirector": "",
            "ponent": "CRISTINA GÓMEZ SEOANE",
            "estudiant": "RAIMON MERCÉ GOTSENS"
        },
        {
            "codi": 152407,
            "titol": "Study of chat bots for internal business applications",
            "inici": "2020-07-02T18:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "GRANT HENDERSON",
            "codirector": "",
            "ponent": "GERARD ESCUDERO BAKX",
            "estudiant": "XAVIER LACASA CURTO"
        },
        {
            "codi": 150897,
            "titol": "Interoperabilitat entre els estàndards actual de seguretat de la informació genòmica",
            "inici": "2020-07-02T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JAIME M. DELGADO MERCE",
            "codirector": "",
            "ponent": "",
            "estudiant": "MARTÍ FERNANDEZ CABALLÉ"
        },
        {
            "codi": 147108,
            "titol": "4G/IoT",
            "inici": "2020-07-02T16:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOSEP ESPUÑA TUYET",
            "codirector": "",
            "ponent": "ANTONIO BENITO MARTÍNEZ VELASCO",
            "estudiant": "MARC URGELL BERNABEU"
        },
        {
            "codi": 145087,
            "titol": "NoC Topology synthesis using metaheuristics",
            "inici": "2020-07-03T12:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "MIQUEL IZQUIERDO USTRELL",
            "codirector": "",
            "ponent": "ROGER ESPASA SANS",
            "estudiant": "JORDI SOLÀ MONTSERRAT"
        },
        {
            "codi": 152867,
            "titol": "Comunicació i tractament de dades en projectes oritentats a l'electrònica de potència",
            "inici": "2020-07-03T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "SILVIA LLORENTE VIEJO",
            "codirector": "",
            "ponent": "",
            "estudiant": "SERGI PUIG SANCHEZ"
        },
        {
            "codi": 152453,
            "titol": "CAPSiDE | NTT - Client Portal",
            "inici": "2020-07-03T09:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "FERRAN GIMÉNEZ",
            "codirector": "PAU CERVERA",
            "ponent": "MARC ALIER FORMENT",
            "estudiant": "ANDREU GALLOFRÉ BAHÓN"
        },
        {
            "codi": 151833,
            "titol": "Transformant Processos de Negoci a Chatbots",
            "inici": "2020-07-03T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JOSE CARMONA VARGAS",
            "codirector": "LLUIS PADRO CIRERA",
            "ponent": "",
            "estudiant": "MOHAMED BENALI BENDAHMANE"
        },
        {
            "codi": 151181,
            "titol": "A flexible proxy for traffic optimization",
            "inici": "2020-07-03T09:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ORIOL ARCAS ABELLA",
            "codirector": "",
            "ponent": "RENE SERRAL GRACIÀ",
            "estudiant": "STEFAN ALEXANDE VAN HEIJNINGEN"
        },
        {
            "codi": 152499,
            "titol": "Detección automática de textos generados automáticamente",
            "inici": "2020-07-03T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARIO MARTÍN MUÑOZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ANTONI CASAS MUÑOZ"
        },
        {
            "codi": 150659,
            "titol": "Towards supporting directive-based programming models composability for heterogeneous computing",
            "inici": "2020-07-03T10:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "A",
            "credits": 30,
            "director": "ANTONIO JOSE PEÑA MONFERRER",
            "codirector": "",
            "ponent": "",
            "estudiant": "ORESTIS KORAKITIS"
        },
        {
            "codi": 154362,
            "titol": "Analysis of learning algorithms for the similarity neural network",
            "inici": "2020-07-03T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "LUIS ANTONIO BELANCHE MUÑOZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "PRAVALLIKA MALLELA"
        },
        {
            "codi": 152874,
            "titol": "Augmented reality multiplayer environment",
            "inici": "2020-07-03T13:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARTA FAIREN GONZALEZ",
            "codirector": "JORDI LUQUE SERRANO",
            "ponent": "",
            "estudiant": "FELIPE RAMIS VASQUEZ"
        },
        {
            "codi": 152454,
            "titol": "Desenvolupament d'un projecte end to end en Business Intelligence",
            "inici": "2020-07-03T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "ANTONIO INVERNON MARQUEZ",
            "codirector": "",
            "ponent": "SILVIA LLORENTE VIEJO",
            "estudiant": "ORIOL FONOLLÀ LLOBET"
        },
        {
            "codi": 152873,
            "titol": "Ampliació de capacitats de la xarxa Garlanet",
            "inici": "2020-07-03T16:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "JOAN MANUEL MARQUES",
            "codirector": "",
            "ponent": "FELIX FREITAG",
            "estudiant": "MARC BLANCA TABENI"
        },
        {
            "codi": 152869,
            "titol": "Estudio, análisis e implementación del entorno productivo para el uso de modelos de Deep Learning",
            "inici": "2020-07-03T15:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "JORDI TORRES VIÑALS",
            "codirector": "",
            "ponent": "",
            "estudiant": "DAVID GARCÍA DOMENECH"
        },
        {
            "codi": 151757,
            "titol": "Sistema de seguridad para moto con alertas",
            "inici": "2020-07-03T10:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "SILVIA LLORENTE VIEJO",
            "codirector": "",
            "ponent": "",
            "estudiant": "GUILLEM AVECILLA GARCÍA"
        },
        {
            "codi": 152564,
            "titol": "Aplicació de desenvolupament de videojocs fàcil per a tothom",
            "inici": "2020-07-03T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARTA FAIREN GONZALEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ÀLEX VALLS TORRES"
        },
        {
            "codi": 152172,
            "titol": "Noves innovacions en serveis de confiança compatibles eIDAS: Cloud and API Management",
            "inici": "2020-07-03T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "B",
            "credits": 18,
            "director": "FRANCISCO JORDAN FERNÁNDEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ARTHUR BERNAL DE OLIVEIRA"
        },
        {
            "codi": 153878,
            "titol": "Gender Bias in Neural Machine Translation: The case of Indian Languages",
            "inici": "2020-07-03T12:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARTA RUIZ COSTA-JUSSA",
            "codirector": "",
            "ponent": "",
            "estudiant": "KESUDH GIRI"
        },
        {
            "codi": 147096,
            "titol": "Blockchain-based Internet reputation system",
            "inici": "2020-07-03T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "PERE BARLET ROS",
            "codirector": "",
            "ponent": "",
            "estudiant": "PAU RISA SUBIRATS"
        },
        {
            "codi": 154351,
            "titol": "Tracing methodologies and tools for JAVA AI and Data Mining frameworks",
            "inici": "2020-07-03T11:30:00",
            "lloc": "Google Meet",
            "pla": "MIRI",
            "modalitat": "B",
            "credits": 30,
            "director": "MARISA GIL GOMEZ",
            "codirector": "",
            "ponent": "",
            "estudiant": "ROBERTO STAGI"
        },
        {
            "codi": 153875,
            "titol": "Fuzzy modeling to deal with uncertainty and explainability",
            "inici": "2020-07-03T11:00:00",
            "lloc": "Hangouts Meet",
            "pla": "GRAU",
            "modalitat": "A",
            "credits": 18,
            "director": "MARIA ANGELA NEBOT CASTELLS",
            "codirector": "",
            "ponent": "",
            "estudiant": "SRIVATHSAN GOVINDARAJAN"
        }
    ],
};
